### ISSUE TITLE
N34 Airway Incomplete

### ISSUE THREAD

**Issue by IslandControl** [IVAO-XU/EI-Sector-File#100]
Airway waypoints along N34 incomplete (airways require all points inside and out of sector to work correctly)

**Comment by Crabcontrollerdave** [comment]
@IslandControl Does P600 and P620 need doing as well?

**Comment by IslandControl** [comment]
Hi Dave,

I think it’s likely there are many that we don’t know, that don’t work.

2 options.

1. Check all airways LL and HL passing through that sector file are
complete end to end

2. Address the fixes for them as they come up.

At the moment we simply haven’t got time to dedicate to option 1 which is
unfortunate, even though I would like to.

Ultimately that means we need to either delay this or add an issue to
review all as a project which I think is a good option.

Or hope someone applies for Shannon CH who would be useful at such a task.


KR

Dan

**Comment by Crabcontrollerdave** [comment]
Alright, Well lets hope someone applies for Shannon CH then.

**Comment by IslandControl** [comment]
If not we will get round to them it’s just capacity at the moment. There’s lots on. On 16 Aug 2024, at 00:26, David ***@***.***> wrote:﻿
Alright, Well lets hope someone applies for Shannon CH then.
