### ISSUE TITLE
Updated EICK Ground layout

### ISSUE THREAD

**Issue by Crabcontrollerdave** [IVAO-XU/EI-Sector-File#13]
Added Buildings, AD Boundary and Taxiway labels. Taxiway centrelines from previous sector file.
![cork ad](https://user-images.githubusercontent.com/97228342/154522536-31a4f415-05c0-43a5-9966-4595d8abd12b.png)

**Comment by chrisglobe** [comment]
Take them off the runway (y)

We can use tools to create the runway markings separately, so the taxiway lines make no sense.

**Comment by Crabcontrollerdave** [comment]
Yeah fully agree Chris, Il work on removing them and get a pull request done soon

**Comment by chrisglobe** [comment]
Great thanks! We're almost at a point we can package this up now for AIRAC 2202 I think, so no rush to get these done for this cycle!
