### ISSUE TITLE
EIDW runway centrelines

### ISSUE THREAD

**Issue by chrisglobe** [IVAO-XU/EI-Sector-File#19]
28L is out of alignment, not checked the others

![image](https://user-images.githubusercontent.com/97064113/154843393-3b9fccbc-9c3d-4ba1-8e14-ee5e13ab1b71.png)

**Comment by Crabcontrollerdave** [comment]
I managed to fix this on my side Chris, all the runways at Dublin were out of alignment il pull request the file soon!

**Comment by chrisglobe** [comment]
Perfect thanks, I've updated the magvar in the .isc file too which should help a bit too (it was -0.1, should be -2!)

**Comment by chrisglobe** [comment]
As we discussed privately this is now sorted through the magvar update!
