### ISSUE TITLE
Dublin Airborne frequencies

### ISSUE THREAD

**Issue by Rbalfour27** [IVAO-XU/EI-Sector-File#30]
I think for new people interested in controlling at Dublin that a list should be made of airborne frequencies and the order they are in e.g.

Departures to the north contact Dublin Lower North
Departures to the south contact Dublin Lower South

**Comment by chrisglobe** [comment]
You can't do this in the sectorfile, we'd need to write it in to the procedures. Best we can do is make sure all the handoffs are set for each ATC position, which I think most are now!

**Comment by chrisglobe** [comment]
Updated the sectorfile to have the proper handoffs set.
